### ISSUE TITLE
Opening someone else's art deletes my work

### ISSUE THREAD

**Issue by maxwofford** [hackclub/blot#170]
Replication steps:

- I clicked a piece in the gallery while my own was open in another tab.
- I closed my own tab
- I clicked "run" on the gallery art
- When I tried to reopen my own game, it was overwritten by the gallery art

**Comment by Sheepy3** [comment]
is this just a result of not having a login system?

**Comment by jianmin-chen** [comment]
I think so - currently we just automatically save whatever's in the editor to `localStorage`. IIRC the account system fixes that, let me check.

**Comment by maxwofford** [comment]
Some of this could be fixed by an account system (ie. I can save), but I also want to flag https://github.com/hackclub/blot/issues/167. It seems like this is caused by trying to use the same URL for multiple states (ie. blot.hackclub.com/editor used for my file, and someone else's file).

Another example of the problem this ticket refers to is running 2 editors in 2 tabs next to eachother. I like to splitscreen and tweak a demo while building my own thing based on it.

**Comment by ozan** [comment]
Perspective of a new user here: this is the most annoying part of an otherwise really lovely experience :) I keep wanting to work on my thing, but have somebody else's thing open too for inspiration etc, but this is not possible.

It seems like the current model of state is: single edited file per browser, persisted locally via `localStorage`. Have you considered using `sessionStorage` instead? That should give you the benefit of not losing changes while a tab is open, but also new state per tab.

(I actually made this fix locally... happy to PR but didn't want to step on anyone's toes)

**Comment by leomcelroy** [comment]
It would be great if you PR'd that @ozan

**Comment by leomcelroy** [comment]
I switched local storage to session storage as discussed above.
