### ISSUE TITLE
console.{log|warn|error} fails on non-chrome browsers

### ISSUE THREAD

**Issue by BrightTheBackpack** [hackclub/blot#214]
in safari, console.log will throw and unhandled promise rejection.

**Comment by V205Arduino** [comment]
I can verify that this is a problem

**Comment by maxwofford** [comment]
Also found in FF ([link to Slack discussion](https://hackclub.slack.com/archives/C04GCH8A91D/p1702947294792299))

**Comment by BrightTheBackpack** [comment]
I will try to fix this tommorow

**Comment by maxwofford** [comment]
After some testing, looks like it's caused by some underlying differences in what `getPosFromErr(new Error('log'))` does in each browser. I think a long term fix is to get that working for all the different browsers, but this should also not be a page breaking change. For now I'm going to submit a PR to catch these errors and force the script to continue. Is there a way to have this report to fullstory or bugsnag or another place we track errors?

**Comment by maxwofford** [comment]
I think I'm going to need some help understanding the `getPosFromError` better before implementing a fix. @leomcelroy, who's best to talk to about that part of the code?
