### ISSUE TITLE
Circle (turtle.arc) isn't accurate when less than a whole number of degrees

### ISSUE THREAD

**Issue by maxwofford** [hackclub/blot#217]
Context here: https://hackclub.slack.com/archives/C04GCH8A91D/p1702967207674719?thread_ts=1702966457.956549&cid=C04GCH8A91D

Screenshot of some lines that should intersect, but the current arc implementation offsets due to accumulated error:
<img width="364" alt="Screenshot 2023-12-19 at 00 30 10" src="https://github.com/hackclub/blot/assets/5891442/2a41240f-1c61-4807-b30a-95f2168f504f">

**Comment by ameya-g-git** [comment]
hey! coded a recreation of the arc function using some basic mathematics and i've found it works better than the current one. it can handle small, decimal angles nicely! 

unsure if i should make a pull request, so ill just put the code i used + a sample screenshot below in markdown

<img width="716" alt="image" src="https://github.com/hackclub/blot/assets/121361927/8c1249b7-9c56-4780-ab7c-c2c2cfcf49bc">

```js
const WIDTH = 125;
const HEIGHT = 125;

function pointCoord(angle, radius) { // returns the coords of a point provided a radius and an angle to subtend around a circle of that radius
  return [
    (Math.cos(angle) * radius) - radius,
    Math.sin(angle) * radius
  ]
};

function arc(angle, radius, points) { // yeahhhhh the main function
  const arc = createTurtle();
  const angleRad = angle * (Math.PI / 180); // i like degrees more don't harsh it

  let arcAngle = 0;

  for (let i = 1; i <= points; i++) { // draws the arc by just going to each point on the circle
    arcAngle += angleRad / points;    
    arc.goTo(pointCoord(arcAngle, radius));
  };
  
  arc.translate( // makes it so that the arc doesn't move around while its size changes
    [WIDTH / 2, HEIGHT / 2],
    [-radius, 0]
  );

  return arc
};

const arc1 = arc(1.7, 47, 74); // example, feel free to plug in whatever values you want !

drawTurtles([arc1]); // draw it
```

**Comment by maxwofford** [comment]
Great work @ameya-g-git! You should totally contribute this in a PR.

I saw some slight differences between the previous arc function and this implementation.

- it takes in a "points" value. It should ideally just figure out how many steps to iterate with.
- it doesn't factor in the current turtle position and rotation.

Want to take another pass on this? It'd be awesome if you patch this up.

**Comment by ameya-g-git** [comment]
thanks for the feedback! here's my thoughts

* the points value was there to give users the ability to resample based on how many points they want, i might just create some sort of function to determine the default value for the points param then
* wdym by factor in the current turtle position and rotation? i was thinking that if the user wanted to transform the arc, they could do so with blot's existing transformation functions, and simply join the turtle once the transformations were complete. should i include parameters to adjust these values?
* as for the off-by-one, im not observing this? the right-most point stays stable no matter how i change the parameters, could you elaborate more?

also, since this isnt exactly art, where would i include my file in the PR? thanks again!

**Comment by leomcelroy** [comment]
Want to try it now Max? I updated the arc implementation to work more like this.
